### ISSUE TITLE
Add Missing Parts of the ICD10

### ISSUE THREAD

**Issue by pwfraley** [dot-base/icd-10-api#45]
### 🚀 Feature Description
As a User, I'd like to get all ICD10 Values, in order to to be more precise in my diagnosis. (For Example the whole F10 area is missing in the data)

**Comment by rti** [comment]
Thanks a lot for the feedback.

We added this to our list. At the moment, we consider this low priority for our use cases. Is this issue critical for your application?

**Comment by pwfraley** [comment]
Sorry for the late feedback.  No it is not critical anymore since we are now using icd11 and created our own API for it.
Thanks for your work.

**Comment by mecklenburg** [comment]
This will become part of #47

**Comment by mecklenburg** [comment]
@pwfraley Thanks again for your feedback.
We will soon update the whole API to ICD11 and ensure all psychiatric diagnosis codes are included with subitems.

**Comment by zanzara** [comment]
>But we are dependent on BfArM support here https://www.bfarm.de/DE/Kodiersysteme/Klassifikationen/ICD/ICD-11/uebersetzung/_node.html and when/how it is supported in billing.

This link above you mentioned, says that they refer online to WHO data.
I'm wondering if they should this   https://icd.who.int/icdapi  as API, where they get the german translation , because they don't exists yet :  https://icd.who.int/icdapi/docs2/SupportedClassifications/

Or am i thinking too noob on that?
